- name: Printing infos ...
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items:
    - "out_dir: {{ out_dir }} (type: {{ out_dir | type_debug }})"
    - "archive: {{ archive }} (type: {{ archive | type_debug }})"
    - "encrypted_archive {{ encrypted_archive }} (type: {{ encrypted_archive | type_debug }})"

- name: Checking parameters to decrypt PKI archive ...
  block:
    - name: Checking for out_dir to be defined ...
      ansible.builtin.assert:
        that:
          - out_dir is defined
        fail_msg: "Parameter 'out_dir' must be defined"
    - name: Checking for archive to be defined ...
      ansible.builtin.assert:
        that:
          - archive is defined
        fail_msg: "Parameter 'archive' must be defined"
    - name: Checking for encrypted_archive to be defined ...
      ansible.builtin.assert:
        that:
          - encrypted_archive is defined
        fail_msg: "Parameter 'encrypted_archive' must be defined"

- name: Make sure that the destination directory does not exist yet ...
  block:
    - name: Stating destination directory ...
      ansible.builtin.stat:
        path: "{{ out_dir }}"
      register: out_dir_stat
    - name: Make sure that the destination directory does not exist ...
      ansible.builtin.assert:
        that:
          - out_dir_stat.stat.exists == false
        fail_msg: "Destination directory \"{{ out_dir }}\" already exists. Remove it by hand or set \"force: true\" to overwrite files in this director<."
      when: force is not defined or force is false

- name: Decrypting and extracting PKI ...
  block:
    - name: Decrypting archive ...
      ansible.builtin.command:
        chdir: "{{ playbook_dir }}"
        cmd: "ansible-vault decrypt {{ encrypted_archive }} --output {{ archive }}"
        creates: "{{ archive }}"

    - name: Creating destination directory ...
      ansible.builtin.file:
        path: "{{ out_dir }}"
        state: directory
        recurse: true

    - name: Extracting archive ...
      ansible.builtin.unarchive:
        src: "{{ archive }}"
        dest: "{{ out_dir | dirname }}"

    - name: Removing decrypted archive ...
      ansible.builtin.file:
        path: "{{ archive }}"
        state: absent
