---
- name: Encrypting PKI archive ...
  connection: local
  hosts: <group>
  run_once: true
  vars:
    run: encrypt
    force: false
  roles:
    - role: shared/pki/roles/generate
    - role: shared/pki/roles/archive