---
- name: Decrypting PKI archive ...
  connection: local
  hosts: <group>
  run_once: true
  vars:
    run: decrypt
    force: false
  roles:
    - role: shared/pki/roles/generate
    - role: shared/pki/roles/archive
