---
- name: Set cfssl vars
  ansible.builtin.set_fact:
    cfssl: "{{ install_cfssl_defaults | combine(cfssl if cfssl is defined else {}, recursive=True) }}"
  tags:
    - install
    - cfssl

- name: Install CFSSL ...
  ansible.builtin.include_tasks:
    file: cfssl.yml
  loop: "{{ cfssl.binary_sources | dict2items }}"
  loop_control:
    loop_var: cfssl_binary
  tags:
    - install
    - cfssl
  when: run is defined and run == "install-cfssl"
