---
- name: Printing infos ...
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items:
    - "pkcs12: {{ pkcs12 }} (type: {{ pkcs12 | type_debug }})"
    - "dest: {{ dest }} (type: {{ dest | type_debug }})"

- name: Checking the Keytool binary ...
  ansible.builtin.command:
    cmd: which keytool
  register: keytool_bin
  changed_when: false

- name: Checking parameters to create a Java KeyStore ...
  block:
    - name: Checking if the keytool binary is available ...
      ansible.builtin.assert:
        that: keytool_bin.rc == 0
        fail_msg: Command "keytool" not found but is required to create Java KeyStores
    - name: Checking for pkcs12 to be defined ...
      ansible.builtin.assert:
        that: pkcs12 is defined
        fail_msg: Parameter 'pkcs12' must be defined as a path to a PKCS#12 archive
    - name: Checking for dest to be defined ...
      ansible.builtin.assert:
        that:
          - dest is defined
        fail_msg: Parameter 'dest' must be defined

- name: Invoking keytool ...
  ansible.builtin.shell:
    cmd: |
      keytool -importkeystore \
        -noprompt \
        -srckeystore {{ pkcs12 }} \
        -srcstoretype pkcs12 \
        -srcstorepass "{{ pkcs12_password | default('') }}" \
        -destkeystore {{ dest }} \
        -deststorepass "{{ password | default('') }}"
    creates: "{{ dest }}"
